import UserType from "./UserType";

export default interface TopicType {
  id: number;
  title: string;
  fancy_title: string;
  slug: string;
  posts_count: number;
  reply_count: number;
  highest_post_number: number;
  image_url: null | string;
  created_at: string;
  last_posted_at: string;
  bumped: boolean;
  bumped_at: string;
  archetype: string;
  unseen: boolean;
  pinned: boolean;
  unpinned: null;
  excerpt?: string;
  visible: boolean;
  closed: boolean;
  archived: boolean;
  bookmarked: null;
  excerpt: string | undefined;
  liked: null;
  tags: unknown[];
  views: number;
  like_count: number;
  has_summary: boolean;
  last_poster_username: string;
  category_id: number;
  pinned_globally: boolean;
  featured_link: null;
  posters: unknown[];
  last_read_post_number?: number;
  details?: {
    notification_level: number;
    can_move_posts: boolean;
    can_edit: boolean;
    can_delete: boolean;
    can_remove_allowed_users: boolean;
    can_create_post: boolean;
    can_reply_as_new_topic: boolean;
    can_flag_topic: boolean;
    can_convert_topic: boolean;
    can_review_topic: boolean;
    can_remove_self_id: 0;
    created_by: UserType;
    last_poster: UserType;
  };
}
